Repository whoant/vy2-fe-voucher-traveloka, pull requests merged in 2022-05, with the labels that each got.

#13 Done
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/Chart/ChartSatistic.jsx
  src/components/CreateVoucher/CreateVoucher.jsx
  src/components/Login/Login.jsx
  src/components/TableDetails/TableDetails.jsx
  src/components/layout/Layout.jsx
  src/components/layout/aside/dark.css
  src/components/layout/aside/light.css
  src/components/layout/brand/dark.css
  src/components/layout/brand/light.css
  src/components/layout/header/base/dark.css
  src/components/layout/header/base/light.css
  src/components/layout/header/menu/dark.css
  src/components/layout/header/menu/light.css
  src/index.css
  src/index.js
  src/pages/Partner/Partner.jsx
  src/plugins.css
  src/prismjs.css
Labels: feature

#17 Partner
  .gitignore
  docker-compose.yml
  package-lock.json
  package.json
  public/env.js
  public/index.html
  src/App.js
  src/api/auth.api.js
  src/api/axiosInstance.js
  src/api/voucherPartner.api.js
  src/components/CreateGift/DataCreateGift.jsx
  src/components/CreateVoucher/CreateVoucher.jsx
  src/components/Gift/DataGift.jsx
  src/components/Login/Login.jsx
  src/components/Register/Register.jsx
  src/components/Voucher/DataVoucher.jsx
  src/components/VoucherItem/index.jsx
  src/components/layout/Layout.jsx
  src/index.js
  src/pages/Partner/CreateGiftPartner.jsx
  src/pages/Partner/Gift.jsx
  src/pages/User/UserVoucher.jsx
Labels: feature

#18 Auto deploy
  .github/workflows/auto-deploy-staging.yml
  Dockerfile
  docker-compose.yml
  nginx.conf
  package-lock.json
  package.json
  src/api/axiosInstance.js
  src/components/Login/Login.jsx
  src/components/Register/Register.jsx
Labels: feature

#20 Fix
  src/App.js
  src/components/Voucher/DataVoucher.jsx
Labels: bug

#21 Feat/detail voucher
  src/App.js
  src/api/voucherPartner.api.js
  src/components/DetailVoucher/index.jsx
  src/components/Voucher/DataVoucher.jsx
  src/components/VoucherItem/index.jsx
Labels: feature

#22 Split route
  src/App.js
  src/components/Login/Login.jsx
  src/components/Register/Register.jsx
  src/components/Voucher/DataVoucher.jsx
  src/components/VoucherItem/index.jsx
  src/components/layout/Layout.jsx
Labels: fix

#24 Add Payment component
  src/App.js
  src/components/Payment/index.jsx
  src/components/Payment/style.css
Labels: fix

#25 Remove Home component
  src/App.js
Labels: fix

#26 Feat/voucher dashboard
  src/App.js
  src/api/voucherPartner.api.js
  src/components/Dashboard/Dashboard.jsx
  src/components/DetailVoucher/index.jsx
  src/components/Voucher/DataVoucher.jsx
  src/components/layout/Layout.jsx
  src/pages/Partner/Partner.jsx
Labels: feature

#27 Feat/home
  package-lock.json
  src/App.js
  src/api/axiosInstance.js
  src/api/voucherUser.api.js
  src/components/Discount/index.jsx
  src/components/Discounts/Discounts.jsx
  src/components/Discounts/style.css
  src/components/Home/Home.jsx
  src/components/Home/style.css
  src/components/Payment/index.jsx
  src/components/Payment/style.css
  src/components/layout/LayoutHome.jsx
Labels: feature

#28 Feat/home
  .github/workflows/auto-deploy-develop.yml
  package-lock.json
  package.json
  src/App.js
  src/api/axiosInstance.js
  src/api/voucherUser.api.js
  src/components/CreateVoucher/CreateVoucher.jsx
  src/components/Discount/index.jsx
  src/components/Discounts/Discounts.jsx
  src/components/Payment/index.jsx
  src/components/PaypalCheckoutButton/index.jsx
  src/hooks/useCountdown.jsx
  src/index.js
Labels: feature

#30 Feat/login
  public/env.js
  src/components/Dashboard/Dashboard.jsx
  src/components/DetailVoucher/index.jsx
  src/components/Discounts/style.css
  src/components/Home/Home.jsx
  src/components/Login/Login.jsx
  src/components/Payment/index.jsx
  src/components/PaypalCheckoutButton/index.jsx
  src/components/Register/Register.jsx
  src/components/Voucher/DataVoucher.jsx
  src/components/layout/LayoutHome.jsx
  src/components/layout/styleHome.css
  src/hooks/useCountdown.jsx
Labels: feature

#31 Update login user
  src/api/auth.api.js
  src/api/axiosInstance.js
  src/components/Login/Login.jsx
  src/components/layout/Layout.jsx
  src/components/layout/LayoutHome.jsx
Labels: fix
