Repository whoant/vy2-fe-voucher-traveloka, pull requests merged in 2022-06, with the labels that each got.

#33 Fix default value
  src/components/Home/Home.jsx
Labels: fix

#34 Sync profile
  src/components/Login/Login.jsx
  src/components/layout/LayoutHome.jsx
Labels: feature

#35 Feat/bonus
  package-lock.json
  package.json
  src/App.js
  src/components/Bonus/Bonus.jsx
  src/components/layout/LayoutHome.jsx
  yarn.lock
Labels: feature

#36 Chore/gift care
  package-lock.json
  package.json
  src/App.js
  src/api/giftCardPartner.api.js
  src/api/giftCardUser.api.js
  src/components/Bonus/Bonus.jsx
  src/components/BonusItem/BonusItem.jsx
  src/components/CreateGift/DataCreateGift.jsx
  src/components/CreateVoucher/CreateVoucher.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/GiftCardItem/index.jsx
  src/components/Login/Login.jsx
  src/components/layout/Layout.jsx
  src/components/layout/LayoutHome.jsx
  src/helpers/combineDescription.js
  src/helpers/money.js
  src/pages/Partner/CreateGiftPartner.jsx
  src/pages/Partner/Gift.jsx
  yarn.lock
Labels: feature

#38 Add detail gift card
  src/App.js
  src/api/giftCardPartner.api.js
  src/components/DetailGiftCard/index.jsx
Labels: feature

#39 Add secret key
  .github/workflows/auto-deploy-develop.yml
Labels: fix

#40 Fix/detail gift card
  src/api/giftCardPartner.api.js
  src/api/voucherPartner.api.js
  src/components/CreateGift/DataCreateGift.jsx
  src/components/CreateVoucher/CreateVoucher.jsx
  src/components/DetailGiftCard/index.jsx
  src/components/DetailVoucher/index.jsx
Labels: fix

#41 Add analyze chart
  src/api/voucherPartner.api.js
  src/components/Chart/ChartSatistic.jsx
  src/pages/Partner/Partner.jsx
Labels: bug
